### ISSUE TITLE
Collection Dispose/Unregister

### ISSUE THREAD

**Issue by psicomante** [maxnowack/signaldb#960] opened 2024-09-23 16:49 UTC
Hello Max,

What do you think about adding a method to dispose/unregister a persistance adapter? E.g. (i'm very dubious about naming)

```ts
// src/Collection/index.ts

// Collection Class, adding method:
public async unregisterPersistenceAdapter() {
  await this.persistenceAdapter?.unregister()
}
```

**Reason**: we should allow *unloading resources* for collections requiring session and connection / disconnection workflow (such as IndexedDB). Moreover I am developing a IndexedDB adapter that sync multiple tabs through `BroadcastChannel` and it requires a `close()` function to disconnect the channel from receiving messages.

**Comment by maxnowack** [comment] 2024-09-26 16:33
I‘ll Work on this soon. Closing as duplicate of #944 🙂

**Closed by maxnowack** 2024-09-26 16:33 UTC
